# Generated by Django 4.0.3 on 2022-03-23 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(verbose_name='age')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
            ],
            options={
                'verbose_name': 'year',
                'verbose_name_plural': 'years',
            },
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(max_length=4, verbose_name='year')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
            ],
            options={
                'verbose_name': 'year',
                'verbose_name_plural': 'years',
            },
        ),
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('film', models.FileField(upload_to='film', verbose_name='film')),
                ('description', models.TextField(max_length=2000, verbose_name='description')),
                ('image', models.ImageField(upload_to='films', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='films.agemodel', verbose_name='age')),
                ('genre', models.ManyToManyField(to='films.genremodel', verbose_name='genre')),
                ('tag', models.ManyToManyField(to='films.tagmodel', verbose_name='tag')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='films.yearmodel', verbose_name='year')),
            ],
            options={
                'verbose_name': 'film',
                'verbose_name_plural': 'films',
            },
        ),
    ]
