# Generated by Django 4.0.3 on 2022-03-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_yearmodel_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('banner_img', models.ImageField(upload_to='banners', verbose_name='banner img')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.filmmodel', verbose_name='film')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
    ]
