# Generated by Django 4.0.3 on 2022-03-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_bannermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='movie_type',
            field=models.CharField(choices=[('1', 'film'), ('2', 'cartoon')], default=2, max_length=20),
        ),
    ]
