# Generated by Django 4.0.3 on 2022-03-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_delete_agemodel_delete_yearmodel_alter_filmmodel_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmmodel',
            old_name='film',
            new_name='film_video',
        ),
    ]
