# Generated by Django 4.0.3 on 2022-03-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_rename_film_filmmodel_film_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='film_video',
            field=models.FileField(upload_to='film', verbose_name='film video'),
        ),
    ]
