# Generated by Django 4.0.3 on 2022-03-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_rename_banner_img_bannermodel_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannermodel',
            old_name='img',
            new_name='banner_img',
        ),
    ]
