# Generated by Django 4.0.3 on 2022-03-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_rename_img_bannermodel_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='description'),
        ),
    ]
