# Generated by Django 4.0.3 on 2022-03-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_alter_filmmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='year')),
            ],
            options={
                'verbose_name': 'year',
                'verbose_name_plural': 'years',
            },
        ),
    ]
