# Generated by Django 4.0.3 on 2022-03-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_alter_yearmodel_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmmodel',
            name='year',
        ),
    ]
