# Generated by Django 4.0.3 on 2022-03-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0019_remove_filmmodel_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.yearmodel', verbose_name='year'),
        ),
    ]
