# Generated by Django 4.0.3 on 2022-03-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_filmmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearmodel',
            name='year',
            field=models.PositiveIntegerField(unique=True, verbose_name='year'),
        ),
    ]
