# Generated by Django 4.0.3 on 2022-03-29 14:22

import config.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0022_alter_yearmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='film_video',
            field=models.FileField(upload_to=config.helpers.UploadTo('film-video'), verbose_name='film video'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='image',
            field=models.ImageField(upload_to=config.helpers.UploadTo('film-image'), verbose_name='image'),
        ),
    ]
