# Generated by Django 4.0.3 on 2022-04-02 08:54

import config.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0023_alter_filmmodel_film_video_alter_filmmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='banner_img',
            field=models.ImageField(upload_to=config.helpers.UploadTo('banners'), verbose_name='banner img'),
        ),
    ]
