# Generated by Django 4.0.3 on 2022-04-03 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_alter_bannermodel_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.yearmodel', verbose_name='year'),
        ),
    ]
