# Generated by Django 4.0.3 on 2022-04-04 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0025_alter_filmmodel_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
    ]
