# Generated by Django 4.0.3 on 2022-04-04 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0026_filmmodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislike', to=settings.AUTH_USER_MODEL, verbose_name='disliked'),
        ),
    ]
