# Generated by Django 4.0.3 on 2022-04-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0028_alter_filmmodel_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'film', 'verbose_name_plural': 'films'},
        ),
    ]
