# Generated by Django 4.0.3 on 2022-04-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0030_alter_filmmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmmodel',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='filmmodel',
            name='likes',
        ),
    ]
