# Generated by Django 4.0.3 on 2022-04-13 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0032_alter_filmmodel_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilmsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.filmmodel', verbose_name='film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'saved film',
                'verbose_name_plural': 'saved films',
            },
        ),
    ]
