# Generated by Django 4.0.3 on 2022-04-12 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_alter_ratingmodel_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
    ]
